export const YASIN_TURKISH = [
  "1. Yâsîn.",
  "2. Hikmet dolu Kur’an’a andolsun ki,",
  "3. Sen hiç şüphesiz gönderilmiş elçilerdensin.",
  "4. Dosdoğru bir yol üzerindesin.",
  "5. Bu Kur’an, mutlak güç sahibi, merhametli Allah tarafından indirilmiştir.",
  "6. Ataları uyarılmamış olan bir kavmi uyarman için (gönderildin). Onlar gaflet içindedirler.",
  "7. Andolsun ki, onların çoğu üzerine söz hak olmuştur; artık onlar iman etmezler.",
  "8. Biz, onların boyunlarına halkalar geçirdik; o halkalar çenelerine dayanmıştır; başları yukarı kaldırılmıştır.",
  "9. Önlerinden bir set, arkalarından bir set çektik; onları kapladık, artık göremezler.",
  "10. Onları uyarsan da uyarmasan da onlar için birdir; iman etmezler.",
  "11. Sen ancak zikre (Kur’an’a) uyan ve görmediği halde Rahman’dan korkan kimseyi uyarabilirsin. Onu bir bağışlanma ve güzel bir mükâfatla müjdele.",
  "12. Ölülere biz hayat veririz, onların yaptıklarını ve geride bıraktıkları eserleri yazarız. Zaten her şeyi apaçık bir kitapta sayıp dökmüşüzdür.",
  "13. Onlara, şehir halkını örnek ver. Hani oraya elçiler gelmişti.",
  "14. Hani biz onlara iki elçi göndermiştik de ikisini yalanlamışlardı. Biz (elçileri) bir üçüncü ile destekledik. Onlar, “Şüphesiz biz size gönderilmiş elçileriz” dediler.",
  "15. Şehir halkı dedi ki: “Siz de bizim gibi insandan başka bir şey değilsiniz. Rahman hiçbir şey indirmemiştir. Siz ancak yalan söylüyorsunuz.”",
  "16. Elçiler şöyle dediler: “Rabbimiz biliyor ki, biz gerçekten size gönderilmiş elçileriz.”",
  "17. “Bize düşen, apaçık bir şekilde duyurmaktan başka bir şey değildir.”",
  "18. Onlar dediler ki: “Biz sizin yüzünüzden uğursuzluğa uğradık. Vazgeçmezseniz sizi taşlarız ve bizden size elem verici bir azap dokunur.”",
  "19. Elçiler şöyle dediler: “Uğursuzluğunuz sizinle beraberdir. Size öğüt verildi diye mi (böyle diyorsunuz)? Hayır, siz ölçüsüz giden bir topluluksunuz.”",
  "20. Şehrin uzak bir köşesinden bir adam koşarak geldi ve dedi ki: “Ey kavmim! Elçilere uyun.”",
  "21. “Sizden bir ücret istemeyenlere uyun; onlar doğru yoldadırlar.”",
  "22. “Beni yaratana kulluk etmeyecek miyim? O’na döndürüleceksiniz.”",
  "23. “O’ndan başka ilahlar mı edineyim? Rahman bana bir zarar dilerse onların şefaati bana hiçbir fayda sağlamaz; beni kurtaramazlar.”",
  "24. “O takdirde ben apaçık bir sapıklık içinde olmuş olurum.”",
  "25. “Şüphesiz ben sizin Rabbinize iman ettim; beni dinleyin.”",
  "26. (Adama) “Cennete gir!” denildi. O şöyle dedi: “Keşke kavmim bilseydi…”",
  "27. “…Rabbimin beni bağışladığını ve beni ikram edilenlerden kıldığını!”",
  "28. Onun ardından kavmine gökten herhangi bir ordu indirmedik; indirecek de değildik.",
  "29. Onlara sadece bir tek çığlık gerekir; bir anda sönüp gittiler.",
  "30. Yazık o kullara! Onlara ne zaman bir elçi gelse mutlaka onunla alay ederlerdi.",
  "31. Kendilerinden önce nice nesilleri helak ettiğimizi görmediler mi? Onlar bir daha dönüp gelmezler.",
  "32. Toplamı istisnasız hepsi huzurumuza toplanacaktır.",
  "33. Onlar için ölü toprak bir delildir. Biz onu diriltir, ondan taneler çıkarırız. İşte onlar ondan yerler.",
  "34. Orada hurmalıklar, üzüm bağları oluşturduk; içlerinde pınarlar fışkırttık,",
  "35. Böylece ürünlerinden yemeleri için. Onları kendi elleriyle mi yaptılar? Hâlâ şükretmezler mi?",
  "36. Yerin bitirdiklerinden, kendi nefislerinden ve daha bilmedikleri şeylerden bütün çiftleri yaratan Allah’ın şanı ne yücedir!",
  "37. Onlar için gece de bir delildir. Gündüzü ondan sıyırırız, bir de bakarsın karanlıktalar.",
  "38. Güneş de kendisine belirlenmiş bir yörüngede akar. Bu, mutlak güç sahibi, her şeyi bilen Allah’ın takdiridir.",
  "39. Ay için de konak yerleri belirledik; sonunda o, eski hurma sapı gibi olur.",
  "40. Güneşin aya yetişmesi, gecenin gündüzü geçmesi mümkün değildir. Her biri bir yörüngede yüzer.",
  "41. Onlar için bir delil de, soylarını dolu gemide taşımamızdır.",
  "42. Onlara bunun gibi binecekleri varlıklar yaratmışızdır.",
  "43. Dilersek onları boğarız; o zaman kendileri için ne bir imdatçı vardır, ne de kurtarılabilirler.",
  "44. Ancak bizden bir rahmet ve bir süreye kadar yararlandırmadır.",
  "45. Onlara, “Önünüzdekinden ve arkanızdakinden sakının ki size merhamet edilsin” denildiği halde, yüz çevirirler.",
  "46. Rablerinin ayetlerinden kendilerine ne zaman bir ayet gelse mutlaka ondan yüz çevirirler.",
  "47. Onlara, “Allah’ın size verdiği rızıktan infak edin” denildiğinde, inkâr edenler iman edenlere: “Allah’ın dileseydi doyuracağı kimseleri biz mi doyuracağız? Siz apaçık bir sapıklık içindesiniz” derler.",
  "48. “Bu tehdit ne zaman gerçekleşecek? Doğru söylüyorsanız söyleyin bakalım.”",
  "49. Onlar sadece bir tek çığlığı beklerler; tartışıp dururlarken onları yakalar.",
  "50. O anda ne bir vasiyette bulunabilirler ne de ailelerine dönebilirler.",
  "51. Sûra üflenmiştir; bir de bakarsın kabirlerinden kalkıp Rablerine doğru akın ediyorlar.",
  "52. “Eyvah bize! Bizi yattığımız yerden kim kaldırdı? Rahman’ın vaat ettiği işte budur; elçiler doğru söylemiş!”",
  "53. Bir tek çığlıktan ibarettir; hepsi huzurumuzda toplanıverirler.",
  "54. Bugün hiç kimse haksızlığa uğratılmaz; ancak yaptıklarınızın karşılığını alırsınız.",
  "55. Cennetlikler bugün neşe içinde bir meşguliyet içindedirler.",
  "56. Kendileri ve eşleri gölgeler içinde koltuklara yaslanmışlardır.",
  "57. Onlar için orada her türlü meyve vardır; istedikleri her şey oradadır.",
  "58. Rahman olan Rabden kendilerine “Selâm!” (denilecektir).",
  "59. “Ey günahkârlar! Bugün siz ayrılın!”",
  "60. “Ey Âdemoğulları! Size, ‘Şeytana kulluk etmeyin, o sizin apaçık düşmanınızdır’ diye emretmedim mi?”",
  "61. “Bana kulluk edin. İşte dosdoğru yol budur.”",
  "62. “Andolsun ki şeytan sizden birçok nesli saptırdı. Hâlâ akletmez misiniz?”",
  "63. “İşte bu, tehdit edilegeldiğiniz cehennemdir.”",
  "64. “Bugün inkâr ettiğiniz için oraya girin.”",
  "65. Bugün ağızlarını mühürleriz; yaptıklarını elleri söyler, ayakları da şahitlik eder.",
  "66. Dileseydik gözlerini silerdik; yola koşmak isterlerdi ama nasıl göreceklerdi?",
  "67. Dileseydik onları oldukları yerde biçimsiz hale getirirdik; ileri de gidemezlerdi geri de dönemezlerdi.",
  "68. Kime uzun ömür verirsek onu yaratılışta başa döndürürüz. Hâlâ akletmezler mi?",
  "69. Biz ona (Peygambere) şiir öğretmedik; bu ona yaraşmaz da. O sadece bir öğüt ve apaçık bir Kur’an’dır.",
  "70. Diri olanları uyarması ve inkârcılar hakkında sözün gerçekleşmesi içindir.",
  "71. Görmediler mi ki, biz onlar için kendi ellerimizin yaptıklarından hayvanlar yaratmışızdır; şimdi onlara sahiptirler.",
  "72. Onları kendilerine boyun eğdirdik; kimine binerler, kimini yerler.",
  "73. Onlarda kendileri için daha nice faydalar ve içecekler vardır. Hâlâ şükretmezler mi?",
  "74. Allah’tan başka tanrılar edindiler; belki yardım görürler diye.",
  "75. Oysa onlar onlara yardım edemezler; aksine onlar, (taptıklarının karşısında) hazır bulunurlar.",
  "76. Onların sözleri seni üzmesin. Şüphesiz biz onların gizlediklerini de açığa vurduklarını da biliriz.",
  "77. İnsan görmez mi ki, biz onu nutfeden yarattık da şimdi apaçık bir hasım kesilmiştir?",
  "78. Bize misal getirdi; kendi yaratılışını unuttu. Dedi ki: “Çürümüş kemikleri kim diriltecek?”",
  "79. De ki: “Onları ilk defa yaratan diriltecek.” O, her türlü yaratmayı bilendir.",
  "80. “O, sizin için yeşil ağaçtan ateş çıkarandır; işte siz ondan yakıyorsunuz.”",
  "81. Gökleri ve yeri yaratan, onların benzerlerini yaratmaya kadir değil midir? Elbette kadirdir; O, yaratıcıdır, bilendir.",
  "82. Bir şeyi diledi mi, O’nun emri sadece: “Ol!” demesidir; o da olur.",
  "83. Her şeyin mülkü elinde olan Allah'ın şanı yücedir. Dönüş O’nadır."
];